# Commit with [ci skip]
git config --global user.email "ac2zoom@yahoo.com"
git config --global user.name "Ac2zoom"

git add .
echo "Added"
git remote rm origin
echo "Removed remote origin"
git remote add origin https://ac2zoom:$GITHUB_API_KEY@github.com/ac2zoom/onnx-backend-scoreboard.git
git add .
git commit -m "New CSVs generated by Travis [skip ci]"
git push origin master
echo -e"Done \ n"
